name: job_tracker
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  hive:
  hive_flutter:
  intl:
  syncfusion_flutter_datepicker: ^29.1.38
  flutter_slidable: ^3.1.2
  percent_indicator: ^4.2.5
  get_it: ^8.0.3
  flutter_screenutil:
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  dartz: ^0.10.1
  flutter_localizations:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
dependency_overrides:
  path_provider_android: 2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # build_runner: ^2.4.6
  # hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/resources/assets/icons/
    - lib/resources/assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: lib/resources/assets/fonts/inter/inter_black.ttf
          weight: 900
        - asset: lib/resources/assets/fonts/inter/inter_extrabold.ttf
          weight: 800
        - asset: lib/resources/assets/fonts/inter/inter_bold.ttf
          weight: 700
        - asset: lib/resources/assets/fonts/inter/inter_medium.ttf
          weight: 500
        - asset: lib/resources/assets/fonts/inter/inter_regular.ttf
          weight: 400
    - family: OpenSans
      fonts:
        - asset: lib/resources/assets/fonts/opensans/OpenSans-Regular.ttf
          weight: 400
